# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
