# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
