# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20160515_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='completed',
            new_name='ishidden',
        ),
    ]
